# plan
### read lines 
### parse each line 
### extract: query, x, y, etc
### create pandas data frame

In [1]:
import json
import pandas as pd

In [9]:
import pandas as pd

chunk_iter = pd.read_json("../../data/example_1k.jsonl", lines=True, chunksize=100)

for i, chunk in enumerate(chunk_iter):
    print(f"Чанк {i}: {len(chunk)} строк")
    display(chunk.head())  # или просто print(chunk.head())

Чанк 0: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
0,37.874904,32.492129,7475f82f-d35f-411c-876b-a233f6cd9d3c,"[None, [9ef9829a-35d6-4d26-a2d2-1e44e3adc2c1],...",1771686554,Geo Agent,Konumumdan en yakın rotayı çıkar,101474,Konya
1,41.011219,28.978176,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,"[None, [c007eac2-d98c-4ddc-818f-2432086ebaa7],...",1772400724,Geo Agent,Takı Dünyası Nerdedir?,11508,Istanbul
2,41.011219,28.978176,0eba2ebf-c5e5-4287-bed0-b76882acda23,"[None, [57178adf-d460-41aa-85f2-d8492219f12d],...",1771065812,Geo Agent,Şuan bulunduğum konumdan bursa görükle ye gide...,11508,Istanbul
3,37.062688,37.379510,ea56cc31-135c-42ca-9f29-0dd20aa4a56d,"[None, [31955092-3872-4116-b726-a8f428e5119a],...",1771742482,Geo Agent,Milano da gezilecek yerler bana söyler misin?,103825,Gaziantep
4,37.181190,33.222247,c12cf199-14c5-47b5-8ca8-7bc258300c38,"[None, [9a1e0b68-4d5a-45cf-a140-7b8c2c575aa1],...",1771836177,Geo Agent,karaman adana arası kaç km ve tır ne yakar,103701,Karaman

Чанк 1: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
100,39.920756,32.854049,f0cbd7c1-732b-4bb7-b732-d8e52fcdb1d3,"[None, [dc909df4-2282-4111-8bfd-7d3b9dca0af7],...",1773204226,Geo Agent,demirci serendi yolu,11503,Ankara
101,38.721882,35.487316,329135c6-2256-4f1d-bbde-491ed7334402,"[None, [faad6925-0e6d-4d1d-a15f-3120d62d5aa0],...",1772599886,Geo Agent,süper bearda hangi yerler var,103831,Kayseri
102,41.734727,27.220516,b73a7e6b-e6ba-449a-b9d8-a0ddd9192411,"[[geo], [79b93937-28ce-4821-972b-1575d4a4c986]...",1773603482,Geo Agent,"taksim,ortaköy,beşiktaş'ı gezmek için aracımı ...",103890,Kirklareli
103,41.011219,28.978176,3cefcd1a-949d-42bb-80a2-ea53e97aeb01,"[None, [55600ce3-4ed4-4136-b4d1-8962e97adf02],...",1771328637,Geo Agent,Sincanda görülmesi gereken yedi yerin bulunduğ...,11508,Istanbul
104,38.429050,27.134203,74276db1-115d-4b98-8aa6-5267e28a2510,"[None, [f183b170-a8a5-44fb-9d4b-ddb9925427d1],...",1773159925,Geo Agent,Izmir dikilden bursa gemlik kaç kilometre,11505,Izmir

Чанк 2: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
200,36.887121,30.703258,267f6654-c9f2-4d73-beb9-fcf5579592e5,"[None, [c31ac428-fb6e-4659-af88-cdbf0f6f885e],...",1772966246,Geo Agent,muğla yol tarifi,107837,Koycegiz
201,36.789533,34.622850,7f508b44-8e95-4a0c-88bd-6d51ed5ca79b,"[None, [2b8158d0-5df9-42ac-8238-54be6971e6d3],...",1772346869,Geo Agent,Kültepe nerede,103831,Kayseri
202,38.377835,27.113922,4a5af4e2-e03a-4d05-9178-1c58f223f19c,"[None, [d56a0dfd-4a78-44b1-8334-d26df90d1d13],...",1772308582,Geo Agent,wifi sorunumu var,11505,Izmir
203,37.874904,32.492129,98ba17e5-85ef-48e7-bfca-32a0a3538b3f,"[None, [7e5989a7-3b4c-4b47-8716-a00d3549b8a3],...",1772919815,Geo Agent,türkmen mobilya yunak,101474,Konya
204,41.011219,28.978176,ab7d39c7-8d60-4c32-bcbc-0aaa0654d721,"[None, [ba4d6e25-7ed9-469f-a7e1-4aca55cb4722],...",1771686858,Geo Agent,kartal'da var mı?,11508,Istanbul

Чанк 3: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
300,40.986908,28.847210,c0f5f42e-214e-4f9b-917d-9e5d447beb4a,"[[geo], [381cb3a3-af68-424e-801f-a0fe6030a5ed]...",1773558626,Geo Agent,Carousel ve kapasite AVM AVM’de kahvaltı yapab...,106119,Bakirkoy
301,41.117914,28.807363,598e3bb7-ef54-40bd-814e-a319b435ea43,"[None, [096ccc3d-61e7-4f9a-9b23-2c4998941fe2],...",1771776447,Geo Agent,Kaç dakikada gelir? Sen ayrıntıla beni bilgile...,115693,Basaksehir
302,38.429050,27.134203,53c332cd-b3b8-4dc3-a8c9-975618151205,"[None, [19fcff93-a4e2-48c7-aaca-dce0c0cfa500],...",1772058327,Geo Agent,Izmir turizm izmirden antalyaya giderken nerel...,11505,Izmir
303,41.011219,28.978176,3647476d-ab1e-463c-8cfd-7adffb15ff7a,"[None, [f69c9a2a-be95-4677-8528-8e2f56c0035a],...",1771359981,Geo Agent,altıntepe kayı kuyumculuk nasıl bir işletme,11508,Istanbul
304,40.815445,30.718152,b70e0163-eea3-4ce5-bbf1-61de8df4cd7e,"[None, [a02d8235-0c11-4223-83fd-73a8767b468e],...",1773192856,Geo Agent,Hendek Kocaeli Yolu,11503,Ankara

Чанк 4: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
400,40.339898,28.777315,b8d26e04-d8e2-41fc-8b8e-b99dc5567e5b,"[None, [d12563c8-f87e-490c-95d0-8fa1aeeff834],...",1771175656,Geo Agent,Diyarbakır'daki laleler,115755,Mudanya
401,40.146675,26.408621,95320ee1-5f51-487c-8e0f-f991fc24c09b,"[None, [860a8c9e-e54a-4682-aa1d-892821f0a1fa],...",1772579753,Geo Agent,Bayramiç'teki klinikleri birlikte incelemek is...,103873,Canakkale
402,41.011219,28.978176,05bd5146-c4f7-43f9-8a57-b85200e1b258,"[None, [2cb6c51d-acf6-4b37-a38d-aa56ede4a88d],...",1772917883,Geo Agent,almanya mercedes benz müzesi,11508,Istanbul
403,41.020405,28.949150,59d2faea-75af-4fa7-aeac-977f9de4ee6f,"[None, [2b781421-7dd3-47b1-a16e-8819a37eca7e],...",1772635806,Geo Agent,Gece kondu garaci tamirciler,115707,Fatih
404,38.500501,43.390431,c04598df-a835-4331-b10c-163d8324990c,"[None, [b77312b3-31af-40cc-a228-f82af8cb81a1],...",1772396460,Geo Agent,Moskova ya 4-6 Mart tarihleri arasından 2 erke...,103861,Van

Чанк 5: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
500,38.429050,27.134203,323055ee-d70f-4d2e-bc77-0ce77815aafd,"[[geo], [1b8f7798-76ea-40f2-bf5e-c3241feb1a07]...",1773433390,Geo Agent,"Yakınımdaki, fast-food olmayan; ev yemeği veya...",11505,Izmir
501,38.429050,27.134203,b5de5593-92c6-478c-a8ae-a0d0f182155a,"[None, [1d980f19-3a0e-40da-8ffb-3e7f3f9702ac],...",1771495047,Geo Agent,Dostum arabamı yıkayacağım. Fakat araba yıkama...,11505,Izmir
502,41.011219,28.978176,84029522-f3b5-43b6-8857-826333e2b61e,"[None, [2e2fcc73-0d84-469e-a229-f28e601f8bf1],...",1771313464,Geo Agent,aracımla gideceğim Kadıköye,11508,Istanbul
503,37.847611,32.456830,a3764dfc-0b35-4552-b02e-0a1745bcef7c,"[None, [bc3af7c6-74a6-4ca7-8137-434144364896],...",1772969141,Geo Agent,konya meram ve karatayda gym saatb23 00 kadar ...,115786,Meram
504,38.429050,27.134203,0e2440ff-8d5b-48d4-9f3a-99dba5e3930c,"[None, [1ddbb8cf-e52d-4c05-9d55-4cd84a2f87d2],...",1773054002,Geo Agent,izmir buca kılınç kuyumcu telefon numarası,115716,Buca

Чанк 6: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
600,41.011219,28.978176,301f2cc2-4907-4a44-b13e-e4f79aea4c0b,"[None, [cb14d1b7-dc11-4796-81a3-3bbf298b3cd6],...",1772111997,Geo Agent,İBB şoför kartı sağlık raporu veren hastaneler...,104756,Kavakli
601,40.188589,29.060814,d564e4cc-a2b9-4539-b7d5-799adbebce65,"[None, [ed529928-9346-416a-9a86-be9a0a602197],...",1771185491,Geo Agent,moskova da en büyük döşeme firmasının adıve a...,11504,Bursa
602,37.002955,35.319457,3fd84bc3-e459-4b92-8648-5d849c5c8b87,"[None, [ab742cbd-7c1f-42e0-ae52-f2c7e4136fde],...",1773312501,Geo Agent,Adana mısır çarşısı,11501,Adana
603,41.011219,28.978176,eb7fef62-5eb9-4432-bbb0-302f4020b666,"[None, [d6a6c097-e6c4-40c4-a375-1f319bb57cc7],...",1773215489,Geo Agent,pendik marmaray,11508,Istanbul
604,39.914786,32.645354,fc5beb8b-7ac4-43db-a8de-057ac730e693,"[None, [c00f1dff-31a2-456f-8bec-e1d266c85e64],...",1772490409,Geo Agent,Ankara’da bu sorunu nerede çözebilirim. bana i...,115679,Etimesgut

Чанк 7: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
700,39.845375,32.557406,a7a4ad3c-855b-45d2-aa9c-28b2d7e5818e,"[None, [73818eb9-18a2-4609-b10c-f8ab301cc1e8],...",1772126772,Geo Agent,Nasıl giderim yapracıktan,115679,Etimesgut
701,40.973115,29.264965,ff4f799c-4201-4f61-b749-11671bbed854,"[None, [672dc352-4646-43c8-824f-0c1ff90991a3],...",1772963170,Geo Agent,Las Tapas Restaurant Istanbul restoran,107755,Sultanbeyli
702,37.435757,27.305614,7ee25415-9934-40cc-922e-ba3db3bd2376,"[None, [fe6b8413-526a-41e1-9355-93e07885428c],...",1772249134,Geo Agent,gümrük tasnif mağazalar ege bölgesindekiler,107939,Didim
703,40.651135,29.259427,583927ea-e9a2-457e-ad89-670643119ed3,"[None, [7743e36b-2943-4003-beb5-a415b516e5f1],...",1773222816,Geo Agent,yalova merkez de is toplantisi nerede yapabilirim,115703,Pendik
704,41.577402,32.634220,cdaaad27-5cde-46b1-a97c-e50d2719a022,"[None, [b5375e8d-379a-4d71-9018-6e8a6fbb4dfd],...",1772174874,Geo Agent,Ferah Baba Türbesi Nerede?,106158,Ulus

Чанк 8: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
800,37.045927,37.408160,487cb86a-8686-4303-8e24-fd7c1d6d9aaa,"[None, [5f1be276-5242-4084-b143-1d046a963275],...",1772685487,Geo Agent,bilgili tekstil yol tarifi,103825,Gaziantep
801,41.279532,32.775563,5277b9bd-9f2b-45f1-ac53-6e3f07c14978,"[None, [0bbc1f5d-1547-4f69-8070-81f2d436d02b],...",1771851637,Geo Agent,temapark nerede,104745,Safranbolu
802,39.920756,32.854049,f5681475-9ad1-4e73-a510-11c784e94ca5,"[None, [15ffeae7-6748-4ec9-b527-0c9665d12bf9],...",1771166009,Geo Agent,Konumumuza göre kasap var mı? Konumumuza göre ...,11503,Ankara
803,39.920756,32.854049,a3ad8359-a2ba-4246-9256-611bf501fb02,"[None, [114de222-b160-4b28-a2f3-b57ab961fdea],...",1771439846,Geo Agent,"Yakınımdaki, fast-food olmayan; ev yemeği veya...",11503,Ankara
804,41.011219,28.978176,40f02b1d-7bb9-41a5-ade6-fdb95939c0c6,"[None, [a2d9085e-e548-47c9-8875-b7cc5636941c],...",1771073534,Geo Agent,"Yakınımdaki, fast-food olmayan; ev yemeği veya...",11508,Istanbul

Чанк 9: 100 строк

,latitude,longitude,message_id,model_response_full,model_response_timestamp,prod_classifier_agent,query,region_id,region_name
900,37.872825,32.492207,03a172eb-b9fe-4cd6-a4a6-44251b60e293,"[None, [2b1055e6-3d8b-41f3-8194-1177eb74409b],...",1772188261,Geo Agent,"Yakınımdaki, fast-food olmayan; ev yemeği veya...",101474,Konya
901,40.188587,29.060814,104646a7-fc68-43e4-8823-a79d8a23f48e,"[[geo], [e9677776-7049-4d94-931d-f99443f12255]...",1773584350,Geo Agent,Bursadan konyaya kaç saatte gidebiliriz?,11504,Bursa
902,40.188589,29.060814,a75f6cc2-fbbe-4b17-952d-3370541487b4,"[None, [a5251a35-8743-4966-b99f-1bb5e8f1d05c],...",1771141564,Geo Agent,Bursa’da Mustafakemalpaşa’ya yakın ya da içind...,11504,Bursa
903,36.891428,30.702484,e3b6bf82-91af-4458-8e9b-f712a48b92a6,"[[geo], [d7a76736-fc3f-46c3-9e3e-4f55251a1ddf]...",1773578996,Geo Agent,Antalya otogarı kemer arabalarının yazıhane il...,115727,Muratpasa
904,36.794487,34.614056,13cff49a-e2e8-4b1f-b4d4-62f932300b13,"[None, [3c6d0a58-7372-4eb5-891a-4af89edae2da],...",1771441709,Geo Agent,"Yakınımdaki, fast-food olmayan; ev yemeği veya...",103715,Mersin

In [3]:
# Берем значение колонки model_response_full из первой строки
sample_response = df.loc[0, "model_response_full"]

print(f"Тип объекта: {type(sample_response)}")
print(f"Длина списка: {len(sample_response)}\n")

# Посмотрим, что лежит под каждым индексом
for i, item in enumerate(sample_response):
    # Ограничим вывод 100 символами, чтобы не засорять экран
    item_str = str(item)[:100] + "..." if len(str(item)) > 100 else str(item)
    print(f"Индекс {i} | Тип: {type(item).__name__} | Значение: {item_str}")

Тип объекта: <class 'list'>
Длина списка: 9

Индекс 0 | Тип: NoneType | Значение: None
Индекс 1 | Тип: list | Значение: ['9ef9829a-35d6-4d26-a2d2-1e44e3adc2c1']
Индекс 2 | Тип: list | Значение: ['7475f82f-d35f-411c-876b-a233f6cd9d3c']
Индекс 3 | Тип: list | Значение: ['default']
Индекс 4 | Тип: list | Значение: ['{"IsCompleteResults":true,"IsFinalMarkdownText":true,"LinksData":[{"Description":"Bts Rota Khimki ...
Индекс 5 | Тип: list | Значение: [[]]
Индекс 6 | Тип: NoneType | Значение: None
Индекс 7 | Тип: NoneType | Значение: None
Индекс 8 | Тип: list | Значение: [[{'content': 'Konumumdan en yakın rotayı çıkar ', 'extra_info': {'timestamp_seconds': '1771686550'}...

In [4]:
import json

# 1. Функция для извлечения Финального Текста (из индекса 4)
def get_final_text(response_list):
    try:
        # Проверяем, что это список и нужный индекс существует
        if isinstance(response_list, list) and len(response_list) > 4:
            payload_str = response_list[4][0]
            
            # Парсим JSON-строку
            data = json.loads(payload_str)
            
            # Достаем ключ TargetMarkdownText
            return data.get("TargetMarkdownText", None)
    except Exception:
        return None

# 2. Функция для извлечения ссылок на источники (из индекса 4)
def get_source_links(response_list):
    try:
        if isinstance(response_list, list) and len(response_list) > 4:
            payload_str = response_list[4][0]
            data = json.loads(payload_str)
            
            # Достаем список ссылок LinksData
            links_data = data.get("LinksData", [])
            
            # Вытаскиваем только сами URL адреса в виде списка
            urls = [link.get("FullUrl") for link in links_data if "FullUrl" in link]
            return urls
    except Exception:
        return []

# 3. Функция для анализа работы агента (из индекса 8)
# Например, посчитаем, сколько сообщений/шагов понадобилось для ответа
def get_agent_steps_count(response_list):
    try:
        if isinstance(response_list, list) and len(response_list) > 8:
            dialog_history = response_list[8][0]
            return len(dialog_history)
    except Exception:
        return 0

# --- ПРИМЕНЯЕМ ФУНКЦИИ К ДАТАФРЕЙМУ ---

# Создаем новые чистые колонки
df['final_answer'] = df['model_response_full'].apply(get_final_text)
df['source_urls'] = df['model_response_full'].apply(get_source_links)
df['steps_count'] = df['model_response_full'].apply(get_agent_steps_count)

# Смотрим на красоту (выведем только нужные колонки)
display(df[['query', 'steps_count', 'source_urls', 'final_answer']].head())

,query,steps_count,source_urls,final_answer
0,Konumumdan en yakın rotayı çıkar,4,"[https://www.cybo.com/RU-biz/bts-rota, https:/...","<media type=""organics_list"" tag=""quick""></medi..."
1,Takı Dünyası Nerdedir?,7,[https://yandex.com.tr/maps/org/taki_dunyasi/1...,"<media type=""organics_list"" tag=""quick""></medi..."
2,Şuan bulunduğum konumdan bursa görükle ye gide...,2,[],"<media type=""organics_list"" tag=""quick""></medi..."
3,Milano da gezilecek yerler bana söyler misin?,2,[],"<media type=""organics_list"" tag=""quick""></medi..."
4,karaman adana arası kaç km ve tır ne yakar,6,[https://yandex.com.tr/maps/983/turkey/routes/...,"<media type=""organics_list"" tag=""quick""></medi..."

In [5]:
def get_organizations(response_list):
    try:
        # Проверяем структуру (как делали раньше)
        if isinstance(response_list, list) and len(response_list) > 4:
            payload_str = response_list[4][0]
            data = json.loads(payload_str)
            
            # Идем по пути: StructuredData -> BlocksData
            blocks = data.get("StructuredData", {}).get("BlocksData", [])
            
            orgs_found = []
            
            # Перебираем все блоки ответа
            for block in blocks:
                # Ищем блок, который содержит список организаций
                if block.get("ContentType") == "OrganizationList":
                    # Достаем сам список
                    organizations = block.get("OrganizationList", {}).get("Organizations", [])
                    
                    # Проходимся по каждой организации и берем ее название (title)
                    for org in organizations:
                        title = org.get("title")
                        # Можно также достать адрес: address = org.get("address")
                        if title:
                            orgs_found.append(title)
                            
            return orgs_found # Возвращаем список найденных названий
            
    except Exception:
        pass
    
    return [] # Если ничего не нашли, возвращаем пустой список

# Применяем новую функцию
df['organizations'] = df['model_response_full'].apply(get_organizations)

# Посмотрим на результат!
display(df[['query', 'organizations', 'final_answer']].head())

,query,organizations,final_answer
0,Konumumdan en yakın rotayı çıkar,[Konya Büyükşehir Belediye Stadyumu],"<media type=""organics_list"" tag=""quick""></medi..."
1,Takı Dünyası Nerdedir?,"[Takı Dünyası, Takı Dünyası]","<media type=""organics_list"" tag=""quick""></medi..."
2,Şuan bulunduğum konumdan bursa görükle ye gide...,[],"<media type=""organics_list"" tag=""quick""></medi..."
3,Milano da gezilecek yerler bana söyler misin?,[],"<media type=""organics_list"" tag=""quick""></medi..."
4,karaman adana arası kaç km ve tır ne yakar,[],"<media type=""organics_list"" tag=""quick""></medi..."

In [6]:
import re

def clean_html_tags(text):
    if not isinstance(text, str):
        return text
    # Удаляем все, что находится внутри < ... >
    clean_text = re.sub(r'<[^>]+>', '', text)
    # Удаляем лишние переносы строк
    return clean_text.strip()

# Применяем очистку к нашей колонке
df['clean_answer'] = df['final_answer'].apply(clean_html_tags)

display(df[['query', 'organizations', 'clean_answer']].head())

,query,organizations,clean_answer
0,Konumumdan en yakın rotayı çıkar,[Konya Büyükşehir Belediye Stadyumu],Araçla Konyaspor Stadyumu’na en yakın rota ve ...
1,Takı Dünyası Nerdedir?,"[Takı Dünyası, Takı Dünyası]",İstanbul'da iki farklı Takı Dünyası mağazası b...
2,Şuan bulunduğum konumdan bursa görükle ye gide...,[],Could you clarify what you’re looking for? I c...
3,Milano da gezilecek yerler bana söyler misin?,[],
4,karaman adana arası kaç km ve tır ne yakar,[],Karaman’dan Adana’ya tır ile ulaşım için **en ...

In [7]:
import json
import pandas as pd

def extract_all_organizations(df):
    """
    Проходит по всему DataFrame, извлекает все организации 
    и возвращает новый "плоский" DataFrame.
    """
    all_orgs = []
    
    # Проходим по каждой строке (каждому запросу) с помощью iterrows()
    for index, row in df.iterrows():
        msg_id = row['message_id']
        response_list = row['model_response_full']
        
        try:
            # Идем к структурам данных
            if isinstance(response_list, list) and len(response_list) > 4:
                payload_str = response_list[4][0]
                data = json.loads(payload_str)
                blocks = data.get("StructuredData", {}).get("BlocksData", [])
                
                # Перебираем блоки в поисках OrganizationList
                for block in blocks:
                    if block.get("ContentType") == "OrganizationList":
                        organizations = block.get("OrganizationList", {}).get("Organizations", [])
                        
                        # Перебираем каждую найденную организацию
                        for org in organizations:
                            
                            # Безопасное извлечение рейтинга (иногда его нет)
                            rating_val = None
                            if "rating" in org and isinstance(org["rating"], dict):
                                rating_val = org["rating"].get("rating")
                            
                            # Безопасное извлечение координат
                            lat, lon = None, None
                            if "coords" in org and isinstance(org["coords"], dict):
                                lat = org["coords"].get("lat")
                                lon = org["coords"].get("long") # Обрати внимание, там ключ "long"
                                
                            # Собираем данные в плоский словарь
                            org_record = {
                                "message_id": msg_id, # Связь с основным запросом!
                                "org_id": org.get("id"),
                                "name": org.get("title"),
                                "address": org.get("address"),
                                "rating": rating_val,
                                "latitude": lat,
                                "longitude": lon
                            }
                            
                            all_orgs.append(org_record)
                            
        except Exception as e:
             # Если что-то сломалось на конкретной строке, пропускаем её
             continue
             
    # Превращаем список словарей в красивый DataFrame
    return pd.DataFrame(all_orgs)

# --- Применяем нашу мега-функцию ---

# Создаем отдельную таблицу только для организаций
df_orgs = extract_all_organizations(df)

print(f"Всего найдено организаций: {len(df_orgs)}")
display(df_orgs.head(10))

Всего найдено организаций: 2212

,message_id,org_id,name,address,rating,latitude,longitude
0,7475f82f-d35f-411c-876b-a233f6cd9d3c,72931290140,Konya Büyükşehir Belediye Stadyumu,"Konya, Selçuklu, Parsana Mah.",4.9,37.946209,32.488097
1,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,157263964577,Takı Dünyası,"İstanbul, Esenyurt, Fevzi Çakmak Cad., 76A",NaN,41.009805,28.694718
2,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,162694159199,Takı Dünyası,"İstanbul, Fatih, Tahtakale Mah., Yavaşça Şahin...",NaN,41.015818,28.968053
3,11cbac8f-c8cb-4dc6-bb72-a8d4d601f023,1077019784,Tursan Plastik,"İstanbul, Sultanbeyli, Mescidi Aksa Cad.",NaN,40.944813,29.282083
4,666b4d5b-a251-4cc5-96d0-203e4e3a16d0,2216045374,Pursaklar,"Pursaklar, Ankara, Türkiye",NaN,40.105252,32.883900
5,147a975e-810c-4882-93f3-8156aa1879c4,2215917761,Araban,"Araban, Gaziantep, Türkiye",NaN,37.420248,37.762902
6,fadcfca3-0d41-4477-ad3c-1d1e8023d4ca,236729402889,Dubai Beach Konyaaltı,"Antalya, Konyaalti, Akdeniz Boulevard",4.6,36.862495,30.639774
7,66d597f3-d050-42bb-afd0-09c02fb04e53,2215973151,Alpaslan Mah.,"Alpaslan Mah., Bayraklı, İzmir, Türkiye",NaN,38.471737,27.164434
8,e4261939-b3c5-4807-8a06-dbec5c98bd35,1160215885,Kanat Dünyası,"İstanbul, Sultangazi, İsmetpaşa Cad., No/89",4.6,41.106558,28.895696
9,e4261939-b3c5-4807-8a06-dbec5c98bd35,116431030475,Bilican Kebap Restoran,Gazi Mah. İsmet Paşa Cd. No: 53/1A Sultangazi/...,4.0,41.103450,28.897289

In [8]:
import json
import pandas as pd

def extract_all_organizations_with_query(df):
    """
    Проходит по всему DataFrame, извлекает все организации, 
    прикрепляя к каждой из них оригинальный query пользователя.
    """
    all_orgs = []
    
    for index, row in df.iterrows():
        msg_id = row['message_id']
        query = row['query'] # <-- Берем query из текущей строки DataFrame
        response_list = row['model_response_full']
        
        try:
            if isinstance(response_list, list) and len(response_list) > 4:
                payload_str = response_list[4][0]
                data = json.loads(payload_str)
                blocks = data.get("StructuredData", {}).get("BlocksData", [])
                
                for block in blocks:
                    if block.get("ContentType") == "OrganizationList":
                        organizations = block.get("OrganizationList", {}).get("Organizations", [])
                        
                        for org in organizations:
                            
                            # Безопасное извлечение рейтинга
                            rating_val = None
                            if "rating" in org and isinstance(org["rating"], dict):
                                rating_val = org["rating"].get("rating")
                            
                            # Безопасное извлечение координат
                            lat, lon = None, None
                            if "coords" in org and isinstance(org["coords"], dict):
                                lat = org["coords"].get("lat")
                                lon = org["coords"].get("long")
                                
                            # Собираем данные
                            org_record = {
                                "message_id": msg_id,
                                "query": query, # <-- ДОБАВЛЕНО СЮДА
                                "org_id": org.get("id"),
                                "name": org.get("title"),
                                "address": org.get("address"),
                                "rating": rating_val,
                                "latitude": lat,
                                "longitude": lon
                            }
                            
                            all_orgs.append(org_record)
                            
        except Exception as e:
             continue
             
    return pd.DataFrame(all_orgs)

# --- Запускаем и смотрим результат ---

df_orgs_with_query = extract_all_organizations_with_query(df)

print(f"Всего найдено организаций: {len(df_orgs_with_query)}")
display(df_orgs_with_query.head(10))

Всего найдено организаций: 2212

,message_id,query,org_id,name,address,rating,latitude,longitude
0,7475f82f-d35f-411c-876b-a233f6cd9d3c,Konumumdan en yakın rotayı çıkar,72931290140,Konya Büyükşehir Belediye Stadyumu,"Konya, Selçuklu, Parsana Mah.",4.9,37.946209,32.488097
1,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,157263964577,Takı Dünyası,"İstanbul, Esenyurt, Fevzi Çakmak Cad., 76A",NaN,41.009805,28.694718
2,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,162694159199,Takı Dünyası,"İstanbul, Fatih, Tahtakale Mah., Yavaşça Şahin...",NaN,41.015818,28.968053
3,11cbac8f-c8cb-4dc6-bb72-a8d4d601f023,Tursan fabrikası nerde?,1077019784,Tursan Plastik,"İstanbul, Sultanbeyli, Mescidi Aksa Cad.",NaN,40.944813,29.282083
4,666b4d5b-a251-4cc5-96d0-203e4e3a16d0,pursaklar konum,2216045374,Pursaklar,"Pursaklar, Ankara, Türkiye",NaN,40.105252,32.883900
5,147a975e-810c-4882-93f3-8156aa1879c4,araban ilçesi,2215917761,Araban,"Araban, Gaziantep, Türkiye",NaN,37.420248,37.762902
6,fadcfca3-0d41-4477-ad3c-1d1e8023d4ca,Dubai Beach Lounge Antalya restoran,236729402889,Dubai Beach Konyaaltı,"Antalya, Konyaalti, Akdeniz Boulevard",4.6,36.862495,30.639774
7,66d597f3-d050-42bb-afd0-09c02fb04e53,bak Alparslan mahallesi bayraklı İzmir'de sim,2215973151,Alpaslan Mah.,"Alpaslan Mah., Bayraklı, İzmir, Türkiye",NaN,38.471737,27.164434
8,e4261939-b3c5-4807-8a06-dbec5c98bd35,Lezzet 5 kpdunu mereye giteveğim,1160215885,Kanat Dünyası,"İstanbul, Sultangazi, İsmetpaşa Cad., No/89",4.6,41.106558,28.895696
9,e4261939-b3c5-4807-8a06-dbec5c98bd35,Lezzet 5 kpdunu mereye giteveğim,116431030475,Bilican Kebap Restoran,Gazi Mah. İsmet Paşa Cd. No: 53/1A Sultangazi/...,4.0,41.103450,28.897289

In [9]:
import json
import pandas as pd

def extract_organizations_with_empty_flag(df):
    all_records = []
    
    for index, row in df.iterrows():
        msg_id = row['message_id']
        query = row['query']
        response_list = row['model_response_full']
        
        # По умолчанию считаем, что организаций не найдено
        organizations_found_for_this_query = False
        
        try:
            if isinstance(response_list, list) and len(response_list) > 4:
                payload_str = response_list[4][0]
                data = json.loads(payload_str)
                blocks = data.get("StructuredData", {}).get("BlocksData", [])
                
                for block in blocks:
                    if block.get("ContentType") == "OrganizationList":
                        organizations = block.get("OrganizationList", {}).get("Organizations", [])
                        
                        # Если список организаций не пустой, значит мы их нашли!
                        if organizations:
                            organizations_found_for_this_query = True
                            
                            for org in organizations:
                                rating_val = None
                                if "rating" in org and isinstance(org["rating"], dict):
                                    rating_val = org["rating"].get("rating")
                                
                                lat, lon = None, None
                                if "coords" in org and isinstance(org["coords"], dict):
                                    lat = org["coords"].get("lat")
                                    lon = org["coords"].get("long")
                                    
                                org_record = {
                                    "message_id": msg_id,
                                    "query": query,
                                    "org_found": True, # <-- Флаг: Организация найдена
                                    "org_id": org.get("id"),
                                    "name": org.get("title"),
                                    "address": org.get("address"),
                                    "rating": rating_val,
                                    "latitude": lat,
                                    "longitude": lon
                                }
                                all_records.append(org_record)
                                
        except Exception as e:
             # Если произошла ошибка при парсинге, мы все равно добавим запись ниже
             pass
        
        # Если после разбора всего JSON мы так и не нашли организаций (или была ошибка парсинга)
        # Добавляем строку с запросом, но пустыми данными об организации
        if not organizations_found_for_this_query:
            empty_record = {
                "message_id": msg_id,
                "query": query,
                "org_found": False, # <-- Флаг: Организации НЕТ
                "org_id": None,
                "name": None,
                "address": None,
                "rating": None,
                "latitude": None,
                "longitude": None
            }
            all_records.append(empty_record)
             
    return pd.DataFrame(all_records)

# --- Запускаем и смотрим результат ---

df_final = extract_organizations_with_empty_flag(df)

print(f"Всего строк в результате: {len(df_final)}")
display(df_final.head(10))

Всего строк в результате: 2387

,message_id,query,org_found,org_id,name,address,rating,latitude,longitude
0,7475f82f-d35f-411c-876b-a233f6cd9d3c,Konumumdan en yakın rotayı çıkar,True,72931290140,Konya Büyükşehir Belediye Stadyumu,"Konya, Selçuklu, Parsana Mah.",4.9,37.946209,32.488097
1,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,True,157263964577,Takı Dünyası,"İstanbul, Esenyurt, Fevzi Çakmak Cad., 76A",NaN,41.009805,28.694718
2,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,True,162694159199,Takı Dünyası,"İstanbul, Fatih, Tahtakale Mah., Yavaşça Şahin...",NaN,41.015818,28.968053
3,0eba2ebf-c5e5-4287-bed0-b76882acda23,Şuan bulunduğum konumdan bursa görükle ye gide...,False,NaN,NaN,NaN,NaN,NaN,NaN
4,ea56cc31-135c-42ca-9f29-0dd20aa4a56d,Milano da gezilecek yerler bana söyler misin?,False,NaN,NaN,NaN,NaN,NaN,NaN
5,c12cf199-14c5-47b5-8ca8-7bc258300c38,karaman adana arası kaç km ve tır ne yakar,False,NaN,NaN,NaN,NaN,NaN,NaN
6,11cbac8f-c8cb-4dc6-bb72-a8d4d601f023,Tursan fabrikası nerde?,True,1077019784,Tursan Plastik,"İstanbul, Sultanbeyli, Mescidi Aksa Cad.",NaN,40.944813,29.282083
7,3d3a476d-03de-4ece-9f9c-bdf66cb196c2,Kızımın adresi,False,NaN,NaN,NaN,NaN,NaN,NaN
8,9e49bd6c-87ac-4b02-a54f-d2e34500c4ef,czech street 126,False,NaN,NaN,NaN,NaN,NaN,NaN
9,666b4d5b-a251-4cc5-96d0-203e4e3a16d0,pursaklar konum,True,2216045374,Pursaklar,"Pursaklar, Ankara, Türkiye",NaN,40.105252,32.883900

In [10]:
import json
import pandas as pd

def extract_organizations_full(df):
    all_records = []
    
    for index, row in df.iterrows():
        msg_id = row['message_id']
        query = row['query']
        response_list = row['model_response_full']
        
        organizations_found_for_this_query = False
        
        try:
            if isinstance(response_list, list) and len(response_list) > 4:
                payload_str = response_list[4][0]
                data = json.loads(payload_str)
                blocks = data.get("StructuredData", {}).get("BlocksData", [])
                
                for block in blocks:
                    if block.get("ContentType") == "OrganizationList":
                        organizations = block.get("OrganizationList", {}).get("Organizations", [])
                        
                        if organizations:
                            organizations_found_for_this_query = True
                            
                            for org in organizations:
                                
                                # --- Извлекаем рейтинг и количество отзывов ---
                                rating_val = None
                                reviews_count_val = None
                                if "rating" in org and isinstance(org["rating"], dict):
                                    rating_val = org["rating"].get("rating")
                                    # Достаем reviewsCount оттуда же, где и сам рейтинг
                                    reviews_count_val = org["rating"].get("reviewsCount")
                                
                                # --- Извлекаем координаты ---
                                lat, lon = None, None
                                if "coords" in org and isinstance(org["coords"], dict):
                                    lat = org["coords"].get("lat")
                                    lon = org["coords"].get("long")
                                
                                # --- Извлекаем тип/категорию организации ---
                                # В твоем JSON это поле "subtitle" (например, "Kuyumcular", "Sanayi kuruluşu")
                                org_type = org.get("subtitle") 
                                
                                # Собираем полные данные
                                org_record = {
                                    "message_id": msg_id,
                                    "query": query,
                                    "org_found": True,
                                    "org_id": org.get("id"),
                                    "name": org.get("title"),
                                    "org_type": org_type,              # <-- ДОБАВЛЕНО: Тип/категория
                                    "address": org.get("address"),
                                    "rating": rating_val,
                                    "reviews_count": reviews_count_val, # <-- ДОБАВЛЕНО: Кол-во отзывов
                                    "latitude": lat,
                                    "longitude": lon
                                }
                                all_records.append(org_record)
                                
        except Exception as e:
             pass
        
        # Если организаций не найдено, добавляем "пустую" строку
        if not organizations_found_for_this_query:
            empty_record = {
                "message_id": msg_id,
                "query": query,
                "org_found": False,
                "org_id": None,
                "name": None,
                "org_type": None,              # <-- Пустое поле для типа
                "address": None,
                "rating": None,
                "reviews_count": None,         # <-- Пустое поле для отзывов
                "latitude": None,
                "longitude": None
            }
            all_records.append(empty_record)
             
    return pd.DataFrame(all_records)

# --- Применяем и любуемся ---

df_final = extract_organizations_full(df)

print(f"Всего строк в результате: {len(df_final)}")
display(df_final.head(10))

Всего строк в результате: 2387

,message_id,query,org_found,org_id,name,org_type,address,rating,reviews_count,latitude,longitude
0,7475f82f-d35f-411c-876b-a233f6cd9d3c,Konumumdan en yakın rotayı çıkar,True,72931290140,Konya Büyükşehir Belediye Stadyumu,Stadyum,"Konya, Selçuklu, Parsana Mah.",4.9,None,37.946209,32.488097
1,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,True,157263964577,Takı Dünyası,Kozmetik ve parfümeri mağazaları,"İstanbul, Esenyurt, Fevzi Çakmak Cad., 76A",NaN,None,41.009805,28.694718
2,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,True,162694159199,Takı Dünyası,Kuyumcular,"İstanbul, Fatih, Tahtakale Mah., Yavaşça Şahin...",NaN,None,41.015818,28.968053
3,0eba2ebf-c5e5-4287-bed0-b76882acda23,Şuan bulunduğum konumdan bursa görükle ye gide...,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,ea56cc31-135c-42ca-9f29-0dd20aa4a56d,Milano da gezilecek yerler bana söyler misin?,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
5,c12cf199-14c5-47b5-8ca8-7bc258300c38,karaman adana arası kaç km ve tır ne yakar,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
6,11cbac8f-c8cb-4dc6-bb72-a8d4d601f023,Tursan fabrikası nerde?,True,1077019784,Tursan Plastik,Plastik ürün üreticileri,"İstanbul, Sultanbeyli, Mescidi Aksa Cad.",NaN,None,40.944813,29.282083
7,3d3a476d-03de-4ece-9f9c-bdf66cb196c2,Kızımın adresi,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
8,9e49bd6c-87ac-4b02-a54f-d2e34500c4ef,czech street 126,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
9,666b4d5b-a251-4cc5-96d0-203e4e3a16d0,pursaklar konum,True,2216045374,Pursaklar,Area,"Pursaklar, Ankara, Türkiye",NaN,None,40.105252,32.883900

In [11]:
import json
import pandas as pd

def extract_ultimate_data(df):
    all_records = []
    
    for index, row in df.iterrows():
        # --- Данные запроса и ПОЛЬЗОВАТЕЛЯ ---
        msg_id = row['message_id']
        query = row['query']
        user_lat = row.get('latitude')       # Широта пользователя
        user_lon = row.get('longitude')      # Долгота пользователя
        user_region = row.get('region_name') # Регион (например, Istanbul)
        
        response_list = row['model_response_full']
        organizations_found_for_this_query = False
        
        try:
            if isinstance(response_list, list) and len(response_list) > 4:
                payload_str = response_list[4][0]
                data = json.loads(payload_str)
                blocks = data.get("StructuredData", {}).get("BlocksData", [])
                
                for block in blocks:
                    if block.get("ContentType") == "OrganizationList":
                        organizations = block.get("OrganizationList", {}).get("Organizations", [])
                        
                        if organizations:
                            organizations_found_for_this_query = True
                            
                            for org in organizations:
                                rating_val = org.get("rating", {}).get("rating") if isinstance(org.get("rating"), dict) else None
                                reviews_count_val = org.get("rating", {}).get("reviewsCount") if isinstance(org.get("rating"), dict) else None
                                org_lat = org.get("coords", {}).get("lat") if isinstance(org.get("coords"), dict) else None
                                org_lon = org.get("coords", {}).get("long") if isinstance(org.get("coords"), dict) else None
                                org_type = org.get("subtitle") 
                                
                                org_record = {
                                    "message_id": msg_id,
                                    "query": query,
                                    "user_region": user_region, # Откуда пришел запрос
                                    "user_lat": user_lat,       # Координаты юзера
                                    "user_lon": user_lon,       # Координаты юзера
                                    "org_found": True,
                                    "org_id": org.get("id"),
                                    "org_name": org.get("title"),
                                    "org_type": org_type,
                                    "org_address": org.get("address"),
                                    "org_rating": rating_val,
                                    "org_reviews_count": reviews_count_val,
                                    "org_lat": org_lat,         # Координаты места
                                    "org_lon": org_lon          # Координаты места
                                }
                                all_records.append(org_record)
                                
        except Exception as e:
             pass
        
        # Если организаций нет
        if not organizations_found_for_this_query:
            empty_record = {
                "message_id": msg_id,
                "query": query,
                "user_region": user_region,
                "user_lat": user_lat,
                "user_lon": user_lon,
                "org_found": False,
                "org_id": None, "org_name": None, "org_type": None, 
                "org_address": None, "org_rating": None, "org_reviews_count": None, 
                "org_lat": None, "org_lon": None
            }
            all_records.append(empty_record)
             
    return pd.DataFrame(all_records)

# --- Создаем наш идеальный датасет ---
df_final = extract_ultimate_data(df)
display(df_final.head())

,message_id,query,user_region,user_lat,user_lon,org_found,org_id,org_name,org_type,org_address,org_rating,org_reviews_count,org_lat,org_lon
0,7475f82f-d35f-411c-876b-a233f6cd9d3c,Konumumdan en yakın rotayı çıkar,Konya,37.874904,32.492129,True,72931290140,Konya Büyükşehir Belediye Stadyumu,Stadyum,"Konya, Selçuklu, Parsana Mah.",4.9,None,37.946209,32.488097
1,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,Istanbul,41.011219,28.978176,True,157263964577,Takı Dünyası,Kozmetik ve parfümeri mağazaları,"İstanbul, Esenyurt, Fevzi Çakmak Cad., 76A",NaN,None,41.009805,28.694718
2,2c53e7c8-ae12-462a-96fe-9c5fdbace8c4,Takı Dünyası Nerdedir?,Istanbul,41.011219,28.978176,True,162694159199,Takı Dünyası,Kuyumcular,"İstanbul, Fatih, Tahtakale Mah., Yavaşça Şahin...",NaN,None,41.015818,28.968053
3,0eba2ebf-c5e5-4287-bed0-b76882acda23,Şuan bulunduğum konumdan bursa görükle ye gide...,Istanbul,41.011219,28.978176,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,ea56cc31-135c-42ca-9f29-0dd20aa4a56d,Milano da gezilecek yerler bana söyler misin?,Gaziantep,37.062688,37.379510,False,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN

In [12]:
# Вывести все уникальные типы (без повторений)
unique_types = df_final['org_type'].unique()
print(unique_types)

<ArrowStringArray>
[                            'Stadyum',    'Kozmetik ve parfümeri mağazaları',
                          'Kuyumcular',                                   nan,
            'Plastik ürün üreticileri',                                'Area',
                          'Restaurant',                            'District',
                            'Restoran',                                'Kafe',
 ...
                   'Motosiklet satışı',                'Evlendirme daireleri',
                              'Çayevi',        'Bilgisayar teknik servisleri',
               'Bilgisayar mağazaları',                      'Hobi kulüpleri',
                'Çitler, parmaklıklar',                'Doğal gaz hizmetleri',
                        'Tüp bayileri', 'Kuruyemiş, atıştırmalık, kuru meyve']
Length: 303, dtype: str